name: Terraform Shenanigans

on:
    push:
        branches: main
    workflow_dispatch:

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: AWS Authentication
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::092376285579:role/github-actions-terraform
                  aws-region: us-east-1
